apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devops-advisor-hpa
  namespace: devops-advisor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devops-advisor-app
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
