apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-argo
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "*"
    helm:
      releaseName: kps-argo
      valueFiles:
        - $values/values-prometheus.yaml
      values: |
        prometheus:
          prometheusSpec:
            serviceMonitorNamespaceSelector: {}
            podMonitorNamespaceSelector: {}
            ruleNamespaceSelector: {}
  - repoURL: https://github.com/anas-443005129/master_projectg6.git
    targetRevision: HEAD
    path: .
    ref: values
    directory:
      recurse: false
      include: |
        values-prometheus.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
