apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-argo     # <— move to its own namespace
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "*"
    helm:
      releaseName: kps-argo         # <— different release name
      valueFiles:
        - $values/values-prometheus.yaml
      # OPTIONAL: let this Prometheus scrape across all namespaces (incl. your old stack)
      values: |
        prometheus:
          prometheusSpec:
            serviceMonitorNamespaceSelector: {}
            podMonitorNamespaceSelector: {}
            ruleNamespaceSelector: {}
  - repoURL: https://github.com/anas-443005129/master_projectg6.git
    targetRevision: HEAD
    path: values                     # or use the include filter if your values stay at repo root
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
