name: Simple DevOps CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Build and Push
      run: |
        docker build -t ${{ secrets.EXISTING_ACR_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:latest .
        az acr login --name ${{ secrets.EXISTING_ACR_NAME }}
        docker push ${{ secrets.EXISTING_ACR_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:latest
    
    - name: Terraform Apply
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
    
    - name: Setup AKS
      run: |
        az aks get-credentials --resource-group ${{ secrets.TERRAFORM_RG }} --name ${{ secrets.AKS_CLUSTER }}
        az aks update -n ${{ secrets.AKS_CLUSTER }} -g ${{ secrets.TERRAFORM_RG }} --attach-acr ${{ secrets.EXISTING_ACR_NAME }}
    
    - name: Deploy App
      run: |
        kubectl create namespace devops-advisor --dry-run=client -o yaml | kubectl apply -f -
        kubectl create secret generic app-secret --from-literal=OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" --from-literal=FLASK_SECRET_KEY="${{ secrets.FLASK_SECRET_KEY }}" -n devops-advisor --dry-run=client -o yaml | kubectl apply -f -
        kubectl create secret generic postgres-secret --from-literal=POSTGRES_USER="${{ secrets.POSTGRES_USER }}" --from-literal=POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" --from-literal=POSTGRES_DB="${{ secrets.POSTGRES_DB }}" -n devops-advisor --dry-run=client -o yaml | kubectl apply -f -
        sed -i "s|devopsaacr.azurecr.io|${{ secrets.EXISTING_ACR_NAME }}.azurecr.io|g" k8s_solution/api-deploy.yml
        kubectl apply -f k8s_solution/
        kubectl wait --namespace devops-advisor --for=condition=ready pod -l app=postgres --timeout=300s
        kubectl wait --namespace devops-advisor --for=condition=ready pod -l app=devops-advisor --timeout=300s
    
    - name: Get Status
      run: |
        kubectl get pods -n devops-advisor
        kubectl get svc -n devops-advisor
        echo " External IP:"
        kubectl get svc devops-advisor-lb -n devops-advisor
